part of '../entities.dart';

@freezed
abstract class SearchItemDetailsEntity with _$SearchItemDetailsEntity {
  const factory SearchItemDetailsEntity({
    required int id,
    ExternalIdEntity? externalId,
    String? name,
    String? alternativeName,
    String? enName,
    @Default([]) List<NameItemEntity> names,
    String? type,
    int? typeNumber,
    int? year,
    String? description,
    String? shortDescription,
    String? slogan,
    String? status,
    RatingEntity? rating,
    VotesEntity? votes,
    int? movieLength,
    String? ratingMpaa,
    int? ageRating,
    ImageObjectEntity? logo,
    ImageObjectEntity? poster,
    ImageObjectEntity? backdrop,
    VideosEntity? videos,
    @Default([]) List<GenreEntity> genres,
    @Default([]) List<CountryEntity> countries,
    @Default([]) List<PersonEntity> persons,
    ReviewInfoEntity? reviewInfo,
    PremiereEntity? premiere,
    @Default([]) List<SeasonsEntity>? seasonsInfo,
    @Default(null) List<SimilarMovieEntity>? similarMovies,
    @Default(null) List<SimilarMovieEntity>? sequelsAndPrequels,
    @Default(null) List<ReleaseYearEntity>? releaseYears,
    int? top10,
    int? top250,
    bool? ticketsOnSale,
    int? totalSeriesLength,
    int? seriesLength,
    bool? isSeries,
    @Default(null) List<String>? lists,
    NetworksEntity? networks,
    DateTime? updatedAt,
    DateTime? createdAt,
  }) = _SearchItemDetailsEntity;
}
